apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: valerauko-net
  labels:
    app: valerauko.net
    role: static
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
      - balint.erdos.tech
      - valerauko.net
  rules:
    - host: balint.erdos.tech
      http:
        paths:
          - backend:
              serviceName: valerauko-net
              servicePort: http
    - host: valerauko.net
      http:
        paths:
          - backend:
              serviceName: valerauko-net
              servicePort: http
